---
title: "STA 210: Regression Analysis"
---

## Overview

Learn approaches for analyzing multivariate data sets, emphasizing analysis of variance, linear regression, and logistic regression. Learn techniques for checking the appropriateness of proposed models, such as residual analyses and case influence diagnostics, and techniques for selecting models. Gain experience dealing with the challenges that arise in practice through assignments that utilize real-world data. This class emphasizes data analysis over mathematical theory.

## Class meetings

|             |             |                            |                     |
|-------------|-------------|----------------------------|---------------------|
| **Lecture** | Section 001 | Mon & Wed 10:15 - 11:30 am | Reuben-Cooke 130    |
|             | Section 002 | Mon & Wed 3:30 - 4:45pm    | Social Sciences 136 |
| **Lab**     | Lab 01      | Thu 3:30 - 4:45pm          | Perkins Link #5     |
|             | Lab 02      | Thu 5:15 - 6:30pm          | Perkins Link #5     |
|             | Lab 03      | Fri 12 - 1:15pm            | Perkins Link #5     |
|             | Lab 04      | Fri 1:45 - 3pm             | Old Chemistry 003   |

## Teaching team

### Instructor

[Maria Tackett](https://www2.stat.duke.edu/~mt324) is an Assistant Professor of the Practice in the Department of Statistical Science at Duke University. Her work focuses on understanding how active learning strategies can be used to promote engagement and student motivation in undergraduate statistics courses. She also studies how classroom practices in introductory math and statistics courses impact students' sense of community, self-efficacy, and learning outcomes.

| Office hours         | Location                                                                                         |
|----------------------|--------------------------------------------------------------------------------------------------|
| Mondays 1 - 2pm      | Old Chem 118B or [Zoom](https://sakai.duke.edu/portal/site/e6f58eb4-029a-4130-bfa3-e5555d967a43) |
| Thursdays 10 - 11am  | [Zoom](https://sakai.duke.edu/portal/site/e6f58eb4-029a-4130-bfa3-e5555d967a43) only             |
| *or by appointment.* |                                                                                                  |

### Teaching assistants

+------------------------------------------------------+--------------------+---------------------------------------------------------------------------------+
| Name                                                 | Office hours       | Location                                                                        |
+======================================================+====================+=================================================================================+
| [Carson Garcia](mailto:carson.garcia@duke.edu)       | Mon 5 - 7pm        | [Zoom](https://sakai.duke.edu/portal/site/e6f58eb4-029a-4130-bfa3-e5555d967a43) |
|                                                      |                    |                                                                                 |
| *TA for Lab 04*                                      |                    |                                                                                 |
+------------------------------------------------------+--------------------+---------------------------------------------------------------------------------+
| [Sara Meta](mailto:sara.mehta@duke.edu)              | Fri 10am - 12pm    | [Zoom](https://sakai.duke.edu/portal/site/e6f58eb4-029a-4130-bfa3-e5555d967a43) |
|                                                      |                    |                                                                                 |
| *TA for Lab 04*                                      |                    |                                                                                 |
+------------------------------------------------------+--------------------+---------------------------------------------------------------------------------+
| [Medy Mu](mailto:han.mu@duke.edu)                    | Tue 4 - 6pm        | [Zoom](https://sakai.duke.edu/portal/site/e6f58eb4-029a-4130-bfa3-e5555d967a43) |
+------------------------------------------------------+--------------------+---------------------------------------------------------------------------------+
| [Glenn Palmer](mailto:glenn.palmer@duke.edu)         | Fri 1:25 - 3:25pm  | Old Chemistry 203B                                                              |
|                                                      |                    |                                                                                 |
| *Head TA\                                            |                    |                                                                                 |
| TA for Lab 03*                                       |                    |                                                                                 |
+------------------------------------------------------+--------------------+---------------------------------------------------------------------------------+
| [Braden Scherting](mailto:braden.scherting@duke.edu) | Mon 2 - 3pm        | Old Chemistry 203B                                                              |
|                                                      |                    |                                                                                 |
| *TA for Lab 02*                                      | Tue 3:15 - 4:15 pm | Old Chemistry 203B                                                              |
+------------------------------------------------------+--------------------+---------------------------------------------------------------------------------+
| [Luke Vrotsos](mailto:luke.vrotsos@duke.edu)         | Tue 6:30 - 8:30pm  | Old Chemistry 025                                                               |
|                                                      |                    |                                                                                 |
| *TA for Lab 01*                                      |                    |                                                                                 |
+------------------------------------------------------+--------------------+---------------------------------------------------------------------------------+
| [Ben Wallace](mailto:ben.wallace@duke.edu)           | Tue 1:30 - 2:30    | [Zoom](https://sakai.duke.edu/portal/site/e6f58eb4-029a-4130-bfa3-e5555d967a43) |
|                                                      |                    |                                                                                 |
|                                                      | Fri 9 - 10am       | Old Chemistry 203B                                                              |
+------------------------------------------------------+--------------------+---------------------------------------------------------------------------------+
| [Aaditya Warrier](mailto:aaditya.warrier@duke.edu)   | Wed 1 - 3pm        | [Zoom](https://sakai.duke.edu/portal/site/e6f58eb4-029a-4130-bfa3-e5555d967a43) |
+------------------------------------------------------+--------------------+---------------------------------------------------------------------------------+
| [Grace Zhao](mailto:zhihui.zhao@duke.edu)            | Tue 11a - 1pm      | [Zoom](https://sakai.duke.edu/portal/site/e6f58eb4-029a-4130-bfa3-e5555d967a43) |
|                                                      |                    |                                                                                 |
| *TA for Lab 01*                                      |                    |                                                                                 |
+------------------------------------------------------+--------------------+---------------------------------------------------------------------------------+

[Click here](https://docs.google.com/spreadsheets/d/1Ay1GxqU2HDpFwnNLZxv0baIAa1lJwUVdtvmprPdkefk/edit?usp=sharing) for full list of office hours.
