## Getting help in the course

We expect everyone will have questions at some point in the semester, so we encourage you to use the following resources for help: 

## Ask questions during lectures and lab

If you have a question during lecture or lab, feel free to ask it! There are likely other students with the same question, so by asking you will create a learning opportunity for everyone.

## Office hours

The teaching team is here to help you be successful in the course. You are encouraged to attend office hours during the times posted on the home page to ask questions about the course content and assignments. A lot of questions are most effectively answered in-person, so office hours are a valuable resource. Please use them!

You can find the schedule for office hours and associated links for online office hours in Sakai.

## Ed Discussion

Outside of class and office hours, any general questions about course content or assignments should be posted on [Ed Discussion](https://edstem.org/us/courses/8350/discussion/). There is a chance another student has already asked a similar question, so please check the other posts on Ed Discussion before adding a new question. If you know the answer to a question that is posted, I encourage you to respond! 

## Email 

If you have questions about personal matters that are not appropriate for the public forum on Piazza (e.g. illness, accommodations, etc.), you may email Professor Tackett at [maria.tackett@duke.edu](mailto:maria.tackett@duke.edu). 


## RStudio Containers

If you're having trouble with your RStudio container...

- First try opening the RStudio container using a different web browser. 
- If you're still having issues, next try restarting the container. [Click here](https://www.introds.org/Restart_Docker_Container.pdf) for instructions on restarting. 
- Lastly, if the issues persist, submit a ticket to OIT and they can look into the issue further. [Click here](https://duke.qualtrics.com/jfe/form/SV_6s3DOsiCIzNya9w) to submit the ticket.


## Additional resources

- [R for Data Science](https://r4ds.had.co.nz/) by Garret Grolemund and Hadley Wickham

- [Beyond Multiple Linear Regression](https://bookdown.org/roback/bookdown-BeyondMLR/) by Paul Roback and Julie Legler

- [Stat2: Modeling with Regression and ANOVA](https://www.amazon.com/STAT2-Modeling-Regression-Ann-Cannon-ebook-dp-B07K6Y99J3/dp/B07K6Y99J3/ref=mt_other?_encoding=UTF8&me=&qid=1629580711) by Ann Cannon et al. 

## Resources for mental health and wellness

- **DukeReach**: Provides comprehensive outreach services to identify and support students in managing all aspects of well being. If you have concerns about a student's behavior or health visit the website for resources and assistance. 
Go to [studentaffairs.duke.edu/dukereach](http://studentaffairs.duke.edu/dukereach)

- **Counseling and Psychological Services (CAPS)**: CAPS services include individual, group, and couples counseling services, health coaching, psychiatric services, and workshops and discussions. Contact CAPS at (919) 660-1000

- **Blue Devils Care**. A convenient and cost-effective way for Duke students to receive 24/7 mental health support through TalkNow. Go to [bluedevilscare.duke.edu](https://www.timely.md/faq/blue-devils-care-faq/)

## Resources for academic support and wellness

- **The Academic Resource Center**: Contact the ARC at (919) 684-5917, [theARC@duke.edu](mailto:theARC@duke.edu), or visit their website [arc.duke.edu](https://arc.duke.edu/)

- **DuWell**: Contact DuWell at (919) 681-8421, [duwell@studentaffairs.duke.edu](mailto:duwell@studentaffairs.duke.edu), or [studentaffairs.duke.edu/duwell](https://studentaffairs.duke.edu/duwell)

- **WellTrack**: Contact WellTrack at [app.welltrack.com](https://app.welltrack.com/)

## **Technology accommodations**

Students with demonstrated high financial need who have limited access to computers may request assistance in the form of loaner laptops.
For technology assistance requests, please go [here](https://keeplearning.duke.edu/technical-support/).
Please note that supplies are limited.

Note that we will be using Duke's computational resources in this course.
These resources are freely available to you.
As long as your computer can connect to the internet and open a browser window, you can perform the necessary computing for this course.
All software we use is open-source and/or freely available.

## **Course materials costs**

There are no costs associated with this course.
All readings will come from freely available, open resources (open-source textbooks, journal articles, etc.).

## **Assistance with Zoom or Sakai**

For technical help with Sakai or Zoom, contact the Duke OIT Service Desk at [oit.duke.edu/help](https://oit.duke.edu/help).
You can also access the self-service help documentation for Zoom [here](https://oit.duke.edu/help/articles/kb0029318) and for Sakai [here](https://sakai-duke.screenstepslive.com/s/sakai_support).

Note that we will be making minimal use of Sakai in this course (primarily for announcements and grade book).
All assignment submission and discussion will take place on GitHub instead.

Zoom will be used for online office hours as well as as a backup option should we need to hold the course online instead of in person.

