---
title: "Week 03"
subtitle: "SLR: Inference"
description: "Lab 02, HW 01, [Statistics experience assigned](https://sta210-fa22.netlify.app/hw/stats-experience.html)"
author: "Sep 12 - 16"
date: ""
tbl-colwidths: [60,40]
title-block-style: none
---

::: callout-important
**Due dates:**

-   AE 03: due Thu, Sep 15 at 11:59pm (on GitHub)
-   AE 04: due Sat, Sep 17 at 11:59pm (on GitHub)
-   Lab 02:
    -   due Mon, Sep 19, 11:59pm (Thu labs)
    -   due Tue, Sep 20, 11:59pm (Fri labs)
-   HW 01: due Wed, Sep 21, 11:59pm
:::

# Prepare

+----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| Reading                                                                                                                                                        | Corresponding lecture |
+================================================================================================================================================================+=======================+
| 📖 IMS, Sec 24.2: [Randomization test for the slope](https://openintro-ims.netlify.app/inf-model-slr.html#randslope)                                           | Sep 12                |
|                                                                                                                                                                |                       |
| 📖 IMS, Sec 24.3: [Bootstrap confidence interval for the slope](https://openintro-ims.netlify.app/inf-model-slr.html#bootbeta1)\                               |                       |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| 📖 IMS, Sec 24.4: [Mathematical model for testing the slope](https://openintro-ims.netlify.app/inf-model-slr.html#mathslope)                                   | Sep 14                |
|                                                                                                                                                                |                       |
| 📖 IMS, Sec 24.5: [Mathematical model, interval for the slope](https://openintro-ims.netlify.app/inf-model-slr.html#mathematical-model-interval-for-the-slope) |                       |
|                                                                                                                                                                |                       |
| 📖 IMS, Sec 24.6: [Checking model conditions](https://openintro-ims.netlify.app/inf-model-slr.html#tech-cond-linmod)                                           |                       |
|                                                                                                                                                                |                       |
| 📖 IMS, Sec 24.7: [Chapter review](https://openintro-ims.netlify.app/inf-model-slr.html#chp24-review)                                                          |                       |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+

# Participate

+-----------------------------------------------------------------------------------------------------------+-------------+
| Topic                                                                                                     | Date        |
+===========================================================================================================+=============+
| 💻 [SLR: Simulation-based inference](../slides/05-slr-sim-inference.qmd) (bootstrap confidence intervals) | Sep 12      |
+-----------------------------------------------------------------------------------------------------------+-------------+
| 💻 [SLR: Simulation-based inference (hypothesis testing)](../slides/06-slr-sim-testing.qmd)               | Sep 14      |
+-----------------------------------------------------------------------------------------------------------+-------------+
| 💻 [Lab 02](../slides/lab-02.qmd)                                                                         | Sep 15 & 16 |
+-----------------------------------------------------------------------------------------------------------+-------------+

# Practice

+------------------------------------------------------------------------------+
| 📋 [AE 03: Bootstrap confidence intervals](../ae/ae-03-bootstrap.qmd)        |
+------------------------------------------------------------------------------+
| 📋 [AE 04: Simulation-based hypothesis testing](../ae/ae-04-sim-testing.qmd) |
+------------------------------------------------------------------------------+

# Perform

+--------------------------------------------------------+---------------------------------+
| Assignment                                             | Due date                        |
+========================================================+=================================+
| 📝 [Lab 02](../labs/lab-02.qmd)                        | Mon, Sep 19, 11:59pm (Thu labs) |
|                                                        |                                 |
|                                                        | Tue, Sep 20, 11:59pm (Fri labs) |
+--------------------------------------------------------+---------------------------------+
| 📝 [HW 01](../hw/hw-01.qmd)                            | Wed, Sep 21, 11:59pm            |
+--------------------------------------------------------+---------------------------------+
| 📝 [Statistics experience](../hw/stats-experience.qmd) | Fri, Dec 09, 11:59pm            |
+--------------------------------------------------------+---------------------------------+
